name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint & format
        run: pnpm check
      - name: Type-check
        run: pnpm typecheck
      - name: Test
        run: pnpm test
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Release packages
        run: pnpm --filter './packages/*' --workspace-concurrency=1 run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
