name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci
      - name: Lint & format
        run: npm run check
      - name: Type-check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Release packages
        run: npm run release --workspaces
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
